{
 "title": "xxx系统数据库监控",
 "description": "使用xshrim/database_exporter进行oracle数据库监控；\n\n",
 "tags": [ "oracle" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(oracle_up, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "数据库", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "数据库状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracle_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "活动会话(USER)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracle_session{instance=\"$host\", status=\"ACTIVE\", type=\"USER\"}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracle_process{instance=\"$host\"}",
     "legendFormat": "current"
    },
    {
     "expr": "oracle_max_process{instance=\"$host\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "执行计数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracle_sysstat{name=\"execute count\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "用户提交数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracle_sysstat{name=\"user commits\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "用户回滚",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracle_sysstat{name=\"user rollbacks\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "慢查询列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "oracle_slowsql{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "等待时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg(oracle_waittime{instance=\"$host\"}) by (waitclass)",
     "legendFormat": "{{waitclass}}"
    }
   ]
  },
  {
   "title": "表空间状态",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "1-(sum(oracle_tablespace{instance=\"$host\",vkind=\"free\"})by(tablespace, type)/sum(oracle_tablespace{instance=\"$host\",vkind=\"total\"})by(tablespace, type))"
    }
   ]
  },
  {
   "title": "资源配额",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max(oracle_resource{instance=\"$host\"}) by (resource, limit)",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}